# -*- coding: utf-8 -*-
from argument import args
from synthesize.main_0 import main as main_0
from synthesize.main_GUIDE import main as main_Guide
from synthesize.main_2 import main as main_2
from validation.main_3 import (
    main as main_3,
)  # The relabel and validation are combined here for fast experiment
import warnings
warnings.filterwarnings("ignore")

def main():
    main_0(args) #select initial random image from the original dataset
    main_Guide(args) #Diffusion moel using Classifier Guidance 
    main_2(args) # RDED after DIF | The images generated by diffusion are cropped as in RDED, then evaluated by the teacher model for selection.
    main_3(args) #Evaluation | Distill
    
if __name__  == "__main__":
    main()
